import { test } from 'node:test';
import assert from 'node:assert/strict';
import net from 'node:net';
import { spawn } from 'node:child_process';

test('isolated HTTP desk: UI, live events, settings, ticket decisions and desktop reviews', async (t) => {
  const socket = net.createServer(); await new Promise((resolve) => socket.listen(0, '127.0.0.1', resolve));
  const port = socket.address().port; await new Promise((resolve) => socket.close(resolve));
  const child = spawn(process.execPath, ['--disable-warning=ExperimentalWarning', 'scripts/local-preview.mjs'], { env: { ...process.env, SIGMADESK_PORT: String(port) }, stdio: ['ignore', 'pipe', 'pipe'] });
  let output = ''; child.stdout.on('data', (s) => { output += s; }); child.stderr.on('data', (s) => { output += s; });
  t.after(async () => { child.kill('SIGTERM'); if (child.exitCode === null) await new Promise((resolve) => child.once('exit', resolve)); });
  const url = `http://127.0.0.1:${port}`;
  let ready = false;
  for (let i = 0; i < 100; i++) {
    try { if ((await fetch(`${url}/api/state`)).ok) { ready = true; break; } } catch { /* booting */ }
    if (child.exitCode !== null) throw new Error(`Preview failed: ${output}`);
    await new Promise((resolve) => setTimeout(resolve, 50));
  }
  assert.ok(ready, output);
  const request = (method, p, b) => fetch(url + p, { method, headers: { 'Content-Type': 'application/json' }, body: b === undefined ? undefined : JSON.stringify(b) });
  const state = await (await request('GET', '/api/state')).json();
  assert.equal(state.settings.paused, 'true'); assert.ok(state.meta.advisors.models.length >= 7); assert.equal(state.meta.background.screen_lock_supported, true);
  assert.ok(state.agents.every((a) => !a.enabled));
  assert.equal(state.meta.preview, true);
  assert.equal((await request('POST', '/api/providers/desktop-usage', { remaining: -1 })).status, 400);
  assert.equal((await request('POST', '/api/providers/desktop-usage', { remaining: 44985, used_month: 14.87 })).status, 200);
  const observed = await (await request('GET', '/api/state')).json();
  assert.equal(observed.meta.usage.perplexity_desktop.credits_remaining, 44985);
  assert.equal((await fetch(`${url}/api/settings`, { method: 'POST', body: '{}' })).status, 415);
  assert.equal((await request('POST', '/api/settings', { key: 'max_concurrent', value: '0' })).status, 400);
  const html = await fetch(url); assert.match(html.headers.get('content-security-policy'), /default-src 'self'/); assert.match(await html.text(), /\/v2\.js/);
  assert.match(await (await fetch(`${url}/classic.html`)).text(), /Reliability/);
  assert.equal((await fetch(`${url}/fonts/ibm-plex-sans-latin-400-normal.woff2`)).headers.get('content-type'), 'font/woff2');
  const engineCatalog = await (await request('GET','/api/engines')).json();
  assert.ok(engineCatalog.seats.find(s=>s.id==='qa').supported_engines.every(e=>e!=='perplexity'));
  assert.equal((await request('POST','/api/team',{seats:{'senior-be':{engine:'codex',model:'',effort:'medium',enabled:false,fallbacks:[{engine:'claude',model:'sonnet',effort:'high'}]}}})).status,200);
  const configured=await (await request('GET','/api/state')).json();
  assert.equal(configured.agents.find(a=>a.id==='senior-be').fallbacks[0].model,'sonnet');
  assert.equal((await request('POST','/api/team',{seats:{qa:{engine:'perplexity',model:'pplx_asi_kimi_k3'}}})).status,400);
  assert.equal((await request('POST','/api/team',{seats:{'senior-be':{fallback_mode:'automatic',enabled:false}}})).status,200);
  const abort = new AbortController(); const stream = await fetch(url + '/api/stream', { signal: abort.signal });
  const reader = stream.body.getReader(); await reader.read();
  const created = await request('POST', '/api/tickets', { title: 'HTTP acceptance fixture', description: 'Verify owner decisions', type: 'bug', priority: 'P1' }); assert.equal(created.status, 201);
  const ticket = await created.json();
  const chunk = await reader.read(); assert.match(new TextDecoder().decode(chunk.value), /HTTP acceptance fixture/); abort.abort();
  assert.equal((await request('PATCH', `/api/tickets/${ticket.key}`, { status: 'invalid' })).status, 400);
  await request('PATCH', `/api/tickets/${ticket.key}`, { status: 'needs_human' });
  const routed = await (await request('POST', `/api/tickets/${ticket.key}/reply`, { body: 'Discuss this design with manager and principal engineers.' })).json();
  assert.equal(routed.message_route, 'discussion'); assert.equal(routed.status, 'needs_human');
  assert.equal((await request('POST', `/api/tickets/${ticket.key}/decision`, { decision: 'correction', message: '' })).status, 400);
  await request('POST', `/api/tickets/${ticket.key}/reply`, { body: 'Use the documented contract' });
  const detail = await (await request('GET', `/api/tickets/${ticket.key}`)).json(); assert.ok(detail.comments.some((c) => c.body.includes('documented contract')));
  const review = await (await request('POST', `/api/tickets/${ticket.key}/architecture-reviews`, { reviewer: 'perplexity/glm-5.3', challenger: 'xai/grok-4.7' })).json();
  assert.equal(review.status, 'awaiting_result'); assert.equal((await request('POST', `/api/architecture-reviews/${review.id}/run`, {})).status, 409);
  const report = await (await request('POST', `/api/architecture-reviews/${review.id}/import`, { result: 'Use atomic reservations and bounded retries.' })).json(); assert.equal(report.status, 'complete');
  assert.equal((await request('POST', `/api/architecture-reviews/${review.id}/import`, { result: 'again' })).status, 409);
  const councils = await (await request('GET', '/api/councils')).json();
  assert.equal(councils.automatic, false); assert.equal(councils.computer.connected, false);
  const demo = councils.councils.find((c) => c.status === 'complete');
  const beforeDecision = await (await request('GET', `/api/tickets/${demo.ticket_key}`)).json();
  const councilDecision = await request('POST', `/api/councils/${demo.id}/decision`, { decision: 'approve', message: 'Demo design accepted' });
  assert.equal(councilDecision.status, 200); assert.equal((await councilDecision.json()).council.decision, 'approve');
  const afterDecision = await (await request('GET', `/api/tickets/${demo.ticket_key}`)).json(); assert.equal(afterDecision.ticket.status, beforeDecision.ticket.status);
  assert.equal((await request('POST', `/api/councils/${demo.id}/decision`, { decision: 'reject' })).status, 409);
  assert.equal((await request('POST', `/api/tickets/${ticket.key}/councils`, { members: [{ model: 'unknown', lens: 'architecture' }, { model: 'claude/sonnet', lens: 'reliability' }] })).status, 400);
  const pendingCouncil = await (await request('POST', `/api/tickets/${ticket.key}/councils`, { members: [{ model: 'perplexity/kimi-k3', lens: 'architecture' }, { model: 'xai/grok-4.7', lens: 'reliability' }] })).json();
  assert.equal(pendingCouncil.status, 'draft');
  assert.equal((await request('POST', `/api/councils/${pendingCouncil.id}/run`, {})).status, 409);
  assert.equal((await request('POST', `/api/councils/${pendingCouncil.id}/cancel`, {})).status, 200);
  assert.equal((await request('POST', '/api/control/start', {})).status, 200);
  assert.equal((await request('POST', '/api/control/stop-all', {})).status, 200);
  await new Promise((resolve) => setTimeout(resolve, 3100));
  const health = await (await request('GET', '/api/health')).json(); assert.equal(health.scheduler.paused, true); assert.ok(health.scheduler.last_tick); assert.equal(health.watch.sources[0].ok, true);
});

test('isolated HTTP desk: research programs, connector governance and the review gate are owner-only, validated endpoints', async (t) => {
  const socket = net.createServer(); await new Promise((resolve) => socket.listen(0, '127.0.0.1', resolve));
  const port = socket.address().port; await new Promise((resolve) => socket.close(resolve));
  const child = spawn(process.execPath, ['--disable-warning=ExperimentalWarning', 'scripts/local-preview.mjs'], { env: { ...process.env, SIGMADESK_PORT: String(port) }, stdio: ['ignore', 'pipe', 'pipe'] });
  let output = ''; child.stdout.on('data', (s) => { output += s; }); child.stderr.on('data', (s) => { output += s; });
  t.after(async () => { child.kill('SIGTERM'); if (child.exitCode === null) await new Promise((resolve) => child.once('exit', resolve)); });
  const url = `http://127.0.0.1:${port}`;
  let ready = false;
  for (let i = 0; i < 100; i++) {
    try { if ((await fetch(`${url}/api/state`)).ok) { ready = true; break; } } catch { /* booting */ }
    if (child.exitCode !== null) throw new Error(`Preview failed: ${output}`);
    await new Promise((resolve) => setTimeout(resolve, 50));
  }
  assert.ok(ready, output);
  const request = (method, p, b) => fetch(url + p, { method, headers: { 'Content-Type': 'application/json' }, body: b === undefined ? undefined : JSON.stringify(b) });
  const research = await (await request('GET', '/api/research')).json();
  assert.ok(research.programs.some((p) => p.id === 'product-discovery')); assert.equal(research.configured, false); assert.equal(research.market_hours.timezone, 'America/New_York');
  assert.equal((await request('POST', '/api/settings', { key: 'research_programs', value: '[]' })).status, 400, 'generic settings cannot bypass program validation');
  const bad = await request('PUT', '/api/research/programs', { programs: [{ ...research.programs[0], review: { minReviewers: 1, reviewers: ['pm'] } }] });
  assert.equal(bad.status, 400); assert.match((await bad.json()).error, /cannot review its own/);
  const saved = await request('PUT', '/api/research/programs', { programs: [{ ...research.programs[0], window: 'off-market', intervalMinutes: 90 }] });
  assert.equal(saved.status, 200); assert.equal((await saved.json()).status.configured, true);
  const state = await (await request('GET', '/api/state')).json();
  assert.equal(state.settings.pm_interval_min, '90'); assert.equal(state.meta.research.programs[0].window, 'off-market'); assert.ok(Array.isArray(state.meta.research_reviews));
  assert.equal((await request('POST', '/api/research/programs/nope/run', {})).status, 404);
  assert.equal((await request('POST', '/api/research/programs/product-discovery/run', {})).status, 409, 'halted desk refuses a run');
  assert.equal((await request('POST', '/api/research/programs/reset', {})).status, 200);
  const CASE = '## Purpose\nx\n## Benefit to the application\nx\n## How it is used\nx\n## SDLC stage improved\ndiscovery\n## Cost\nx\n## Time\nx\n## Data leaving the machine\nx\n## Risks and fallback\nx\n## Success measure\nx';
  assert.equal((await request('POST', '/api/connectors', { name: 'sec-filings', case_md: '## Purpose\nonly' })).status, 400);
  assert.equal((await request('POST', '/api/connectors', { name: 'sec-filings', purpose: 'EDGAR filings', case_md: CASE })).status, 201);
  assert.equal((await request('POST', `/api/connectors/sec-filings/approve`, { binding: { type: 'http', url: 'https://x.example/mcp' }, tools: ['search'] })).status, 400, 'no approval without an assessment');
  assert.equal((await request('POST', `/api/connectors/sec-filings/assess`, {})).status, 200);
  const list = await (await request('GET', '/api/connectors')).json();
  assert.equal(list.connectors.find((c) => c.name === 'sec-filings').status, 'assessing'); assert.equal(list.case_sections.length, 9);
  assert.equal((await request('POST', `/api/connectors/sec-filings/reject`, { reason: 'not now' })).status, 200);
  const created = await (await request('POST', '/api/tickets', { title: 'Owner ticket', description: 'd', type: 'task', priority: 'P2' })).json();
  assert.equal((await request('POST', `/api/tickets/${created.key}/research-review/waive`, { note: 'x' })).status, 400, 'only research proposals carry the gate');
});
